version: "3.9"
services:
  inventory-service:
    container_name: inventory-service
    image: inventory-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-server:29092
    networks:
      - backend

networks:
  backend:
    external: true